FROM bitnami/mongodb:4.0-ol-7

# This should be injected in runtime but
# I'll keep it here for time reasons :(
ENV MONGODB_USERNAME=toe
ENV MONGODB_PASSWORD=t1ct4ct0e
ENV MONGODB_DATABASE=tictactoe

VOLUME /bitnami

EXPOSE 27017