export const gameConfigConstants = {
  BOARD_SIZE_SET: 'BOARD_SIZE_SET',
  GAME_CONFIG_CLEAR: 'GAME_CONFIG_CLEAR',
  GAME_CONFIG_MODAL_SET: 'GAME_CONFIG_MODAL_SET',
  PLAYER_1_CLEAR: 'PLAYER_1_CLEAR',
  PLAYER_1_ERROR: 'PLAYER_1_ERROR',
  PLAYER_1_SET: 'PLAYER_1_SET',
  PLAYER_2_CLEAR: 'PLAYER_2_CLEAR',
  PLAYER_2_ERROR: 'PLAYER_2_ERROR',
  PLAYER_2_SET: 'PLAYER_2_SET',
};

export const gameStatusConstants = {
  BOARD_STATE_SET: 'BOARD_STATE_SET',
  GAME_FINISH: 'GAME_FINISH',
  GAME_RESTART: 'GAME_RESTART',
  MOVE_COUNTER_INCREMENT: 'MOVE_COUNTER_INCREMENT',
  WINNER_SET: 'WINNER_SET',
};

export const helpConstants = {
  HELP_MODAL_SET: 'HELP_MODAL_SET',
};

export const scoreConstants = {
  SCORE_DRAW_INCREMENT: 'SCORE_DRAW_INCREMENT',
  SCORE_PLAYER_1_INCREMENT: 'SCORE_PLAYER_1_INCREMENT',
  SCORE_PLAYER_2_INCREMENT: 'SCORE_PLAYER_2_INCREMENT',
};
