export const gameConfigConstants = {
  GAME_CONFIG_CLEAR: 'GAME_CONFIG_CLEAR',
  PLAYER_1_CLEAR: 'PLAYER_1_CLEAR',
  PLAYER_1_SET: 'PLAYER_1_SET',
  PLAYER_2_CLEAR: 'PLAYER_2_CLEAR',
  PLAYER_2_SET: 'PLAYER_2_SET',
  BOARD_SIZE_SET: 'BOARD_SIZE_SET',
};
