export const gameConfigConstants = {
  BOARD_SIZE_SET: 'BOARD_SIZE_SET',
  GAME_CONFIG_CLEAR: 'GAME_CONFIG_CLEAR',
  GAME_CONFIG_MODAL_SET: 'GAME_CONFIG_MODAL_SET',
  PLAYER_1_CLEAR: 'PLAYER_1_CLEAR',
  PLAYER_1_ERROR: 'PLAYER_1_ERROR',
  PLAYER_1_SET: 'PLAYER_1_SET',
  PLAYER_2_CLEAR: 'PLAYER_2_CLEAR',
  PLAYER_2_ERROR: 'PLAYER_2_ERROR',
  PLAYER_2_SET: 'PLAYER_2_SET',
};

export const helpConstants = {
  HELP_MODAL_SET: 'HELP_MODAL_SET',
};
